name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.swift'
      - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:latest'
    container:
      image: ${{ matrix.image }}
    env:
      CONTROL_DB_URL: "postgresql://fake:fake@localhost:5432/fake"
      SUPABASE_MANAGEMENT_API_KEY: "fake-key"
      SUPABASE_MGMT_KEY: "fake-key"
      SUPABASE_ORGANIZATION_ID: "fake-org"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: swift build
